server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
  # 日期格式化，加了拦截器之后会失效
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 支付宝的配置
# appId
alipay.appId: 9021000134673866
# 应用私钥
alipay.appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQChbgRtBdS2rMTW+mBt8owMiuI7iL0j1yt8CE/gAEimOcrM4vw9G/OOSijtyhVgVSTTmWzENWjOYrczy4GgZxnM4wPfZqYCOeazS3qpYwY7khbr0XD5AEqZ7fXOwifz4XcRHOsB7vsOch8uFjvrzqkyFvW/zGxf0Bs8GgB6ZgS7gBx2Efav4eqkk4nKm0i4iVc5ewkjmD8vuSMMLssc7/eG5/3mzkX2r2qKT9wxWiFKfsEBSBcz/gEOlWAfhCJs7D4tkCuui1A6WD/b1bhzbj0wMqz84wl7tc2m84w646Mk3AKQzWAQhcJbyYI12pACSwRXQwYIrbIHFnDBALs5e4t5AgMBAAECggEAez7WjDHec9U1tveS9X4vJEhIbrF3zcwx+9EQwnEVBiurRH+rmjAj46eE1f7qEREQO6iwHKC2MpO1UQr3HXJ5hS5wv3fMGHkCRDLFJFtg38wqScIuYTyyuBCwETm0bQLe96a/WUuOSzofyfzZpK+0B3T2DIfS2de1Y05qvQf0Zv0w6/GJ+Iz2ZPO/46/mW8zPLpv2HHE3QhhecYZWeKJtukk/fl6GEL4FwgVL1qQkOg3C8vXBXeP9ggSG5l8oUXKb/34ffLGYejd+o5Bx4HOZUwv+lkqkVZXNg07dQip5qdV74IZZ6E0U9qyZz5YR08rPvx3CLHXk1Y76dPe6g7ylsQKBgQDjHcTCJVIYFplIFKT+HITpoEVO5WMq2Yo1Kgpa/E/ufChrn8SzhHM9cOOj+xPaRsw9YuvebIwknc+XtSsCHjOdAaqLJuo7KpAMANkIHoP6jSegdo1SV5bl2/QCOSZ3xyjOTZ7AWqQB1/3RGWi41jzRWgGhDsc/mIoBsU+Cpv8gRQKBgQC19bDEHNSP1PJY9nIENYTsBJZgymPyhpjGYpnzsPB5SuSa68vUe4QLP7Vn0hMed0Bu7zDhAjxXYLZD4/XDBuhT4eCL6/tz4+tL+/EFZyXGj3iiXiomqErezYdlxvu9LBCcaDauFZMDm5BMR+jGUG9fX+RteTJCtWwSiUhzGgYzpQKBgHZxVeVyFSge0P14Vrt3IBG+1aZZlqgIHz2umQvuPbk/4syN28VLM9Y9A1rHXAkflvAEoMG0ljmaW2LgxncqTPx6m/hJ6SnF/q1j28uSLn4CE0Jp0TW6HCXv2Yc3Ssp4gN1mOX5TRuj3PZVIzQZoI/uCFwtpa5vM71wGnlKiyLaJAoGAaU7FO+rXllqO26/dstPqltHc2i2oBI+jUYV1RhUMR5ZxkbuP3uyRMhVv/qMVD5fCwbFK3550n7lIIyiGbpXL1egvFavAfoTVA8fO6OqWcUFNduL6kB7sHeBjUSMFRKmA/5RMuRmhWQAqVgt0C3o3ysHrqPPwg60N2/h55quUFUUCgYBtMczdJqyBgacTHqye0yTBbQc8lFfZYx2tFEY2Jl9J+fwH2uPfecYrgb6La6rwV5Rqxtk8nX5+uP7y11B6wQTTfaHNKAfnsjGXmTqlJ9DzwjPXazbF1j8a/ULPnwdepAmi5Qou8ln4Aidrm4RCzKc5PGqvsQKhHEkJPNMFtKGMug==
# 支付宝公钥
alipay.alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzfaoQ2h8A019IjAP8AogqHhqV1ANmjEtpTe6/Fo2JbN2QMoAYchFNq83oVPGIvDw1C6w+IjUbTr1LHIA7l2EJQjWcxaXej5ltdjwZGxdE9ngnAbnzrwfRhrysgcxyPg9Q7oyaZngadUohxPjI5e+byZn1ybgMW5+X3JLuu25fbKWH8VxB6f8DYtugpHYtPjE1qFhWdSU9L+F7uSTpvEv7Nj/D6nSe2cmWhfjJdQMYI+S+PLNoGxbAmMkscfwK7bBMifEnZFMhaGi1V2oRr6tCSCHtZqkcaLeoEToYv1Gg06xCa/Ocl5b0ciWAO4IQXHyvPoOrMJogKws3xK9qg/zQQIDAQAB
# 支付成功回调地址，这里使用 netapp 内网穿透，每次启动 netapp 的网址都会变化，但是回调的接口 alipay/notify 不变
alipay.notifyUrl:  http://ukhne9.natappfree.cc/alipay/notify

# 买家账号
#  uhslhy6615@sandbox.com